apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ansible
  template:
    metadata:
      labels:
        app: ansible
    spec:
      containers:
        - name: ansible
          image: afif1400/ansible-service
          resources:
            requests:
              cpu: 500m
              memory: 1024Mi
            limits:
              memory: "3072Mi"
              cpu: "1000m"

---
apiVersion: v1
kind: Service
metadata:
  name: ansible-srv
spec:
  selector:
    app: ansible
  ports:
    - port: 5000
      targetPort: 5000
      name: ansible
      protocol: TCP
