apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: afif1400/auth-service
          resources:
            requests:
              memory: 1024Mi
              cpu: 500m
            limits:
              memory: "3072Mi"
              cpu: "1000m"

---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - port: 5000
      targetPort: 5000
      name: auth
      protocol: TCP
