apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-manager-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-manager
  template:
    metadata:
      labels:
        app: image-manager
    spec:
      containers:
        - name: image-manager
          image: afif1400/image-service
          resources:
            requests:
              cpu: 500m
              memory: 1024Mi
            limits:
              memory: "3072Mi"
              cpu: "1000m"

---
apiVersion: v1
kind: Service
metadata:
  name: image-manager-srv
spec:
  selector:
    app: image-manager
  ports:
    - name: image-manager
      protocol: TCP
      port: 5000
      targetPort: 5000
